name: av-pino-motor-fault-diagnosis
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - scikit-image>=0.19.0
  - h5py>=3.6.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  - mypy>=0.991
  
  - pip
  - pip:
    - omegaconf>=2.1.0
    - plotly>=5.0.0
    - nbconvert>=6.4.0
    
    # Optional dependencies for advanced features
    # - onnx>=1.12.0
    # - onnxruntime>=1.12.0